name: 'Update submodules'

on:
  workflow_dispatch:
  # run every 72 hours (every 3 days)
  schedule:
    - cron: "0 0 */3 * *"  # This runs at midnight UTC every 3rd day

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Update submodules to latest commit
        run: git submodule update --remote --force

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated submodule update"
          git push origin HEAD:automated-submodule-update

      - name: Create Pull Request using peter-evans/create-pull-request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated submodule update"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: automated-submodule-update
          delete-branch: true
          title: '[Automated] Submodule update'
          body: |
            Submodule update
            - Auto-generated by [create-pull-request][1]
          reviewers: |
            editorial
          draft: false
